name: CI

on: [push, pull_request, check_run]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v1
      with: 
        python-version: 3.8
    - name: Prepare environment
      run: |
        python -m pip install --upgrade pip
        python setup.py develop
        pip uninstall pyasp --yes
        pip install pyasp==1.4.3 --no-cache-dir

    - name: Build meneco
      run: |
        python setup.py install

    - name: Test using pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov --cov-report=term-missing -vv

    - name: Sonarqube code quality
      uses: sonarsource/sonarcloud-github-action@master
      if: env.SONAR_TOKEN != ''
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_AUTH_TOKEN }}
        SONARCLOUD_URL: https://sonarqube.inria.fr/sonarqube
      with:
        args:
          -Dsonar.host.url=${SONARCLOUD_URL}
          -Dsonar.login="'${env.SONAR_TOKEN}'"
